apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    environment: learning
spec:
  containers:
    - name: nginx
      image: nginx:1.24
      ports:
        - containerPort: 80
